
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Or your default branch

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build project
        run: npm run build
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
          
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4
      
      # Create .nojekyll file to prevent Jekyll processing
      - name: Create .nojekyll file
        run: |
          touch dist/.nojekyll
          echo "# This file prevents GitHub Pages from using Jekyll processing" > dist/.nojekyll
      
      # Add a debug step to check the content of the dist directory
      - name: List dist directory content
        run: ls -la dist/
      
      # Use explicit version for upload-pages-artifact (v1)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'dist'
      
      # Use explicit version for deploy-pages (v2)
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
